steps:
  # 1. Docker 이미지 빌드 (Dockerfile 경로를 명시적으로 지정)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile',
      '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/msds-search/msds:$COMMIT_SHA',
      '.'
    ]

  # 2. 빌드된 이미지를 Artifact Registry에 업로드(Push)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/msds-search/msds:$COMMIT_SHA'
    ]

  # 3. Cloud Run에 서비스 배포 (서비스명: msds-service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'msds-service'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/msds-search/msds:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout=3600'
      - '--set-env-vars'
      - 'PYTHONUTF8=1,PYTHONIOENCODING=utf-8,GCS_BUCKET=msdsdata'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-northeast3:msds-db'
      - '--set-secrets'
      - 'ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest,ADMIN_ID=ADMIN_ID:latest,ADMIN_PW=ADMIN_PW:latest'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/msds-search/msds:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
